### ISSUE TITLE
Running tests on multiple projects

### ISSUE THREAD

**Issue by cherrydev** [xunit/dnx.xunit#25]
Right now, the only way that I can find to run tests on multiple projects at the same time is to make a new project that depends on all of the tests projects and then pass the names of the other projects as arguments.  Is there something that I'm missing?  If not, is this functionality that will be coming now that 'global' commands are a reality?

**Comment by bradwilson** [comment]
I don't believe there's going to be any way for us to do this, given the architecture of DNX. Maybe @davidfowl or @damianedwards can offer some thoughts.

**Comment by cherrydev** [comment]
DNX supports the concept of "project folders" being loaded as assemblies.  It basically uses the project.json as a surrogate.  Take a look at IMetadataProjectReference.  I wish I knew more about how the internals of it worked.

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#488
