### ISSUE TITLE
Add support for injecting dnx hosting services into test classes

### ISSUE THREAD

**Issue by davidfowl** [xunit/dnx.xunit#27]
It would be great if hosts could take part in the construction of test classes We could avoid this:

https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNet.Server.KestrelTests/EngineTests.cs#L34

**Comment by bradwilson** [comment]
You should be able to do this with a custom Fact and discoverer, since the discoverer is responsible for picking the method arguments.

**Comment by davidfowl** [comment]
Oh show me how. This is something that should be built into the dnx runner

**Comment by bradwilson** [comment]
We're not going to build this into the runner.

Runners are intended to be as independent of the test framework and the environment as possible. For starters, this is the ***DNX*** runner, not the ***ASP.NET*** runner. Second, taking dependencies like this would tie the runner to a specific version of ASP.NET, which is not desired behavior.

The best place for things like this would be in a unit test support library.

As for the implementation, there are several [sample projects](https://github.com/xunit/samples.xunit) that show custom Facts. The simplest is probably the [custom STA fact and theory sample](https://github.com/xunit/samples.xunit/tree/d574fa9677eb2089d7acf6084767237e20f38dd6/STAExamples).

**Comment by davidfowl** [comment]
> For starters, this is the DNX runner, not the ASP.NET runner.

Which is exactly why it makes sense to put this logic in the dnx runner. These services are from the dnx environment.

> Second, taking dependencies like this would tie the runner to a specific version of ASP.NET, which is not desired behavior.

Nope. The IServiceProvider is injected into the Program.cs of the runner so you aren't tied to any specific version of the runner.

That sample looks like the opposite of what I want. I just need a way to flow DNX services from the runner's Program.Main to the test itself.

**Comment by bradwilson** [comment]
About the closest we would want to get is to put the `IServiceProvider` into the `CallContext`. You'd still need to write custom code somewhere to get it injected.

**Comment by davidfowl** [comment]
@bradwilson we do that already thats the entire purpose of this bug. To avoid having our test have to get at the static. Lesser of 2 evils?

**Comment by bradwilson** [comment]
The runner has no capability to inject anything into any tests. It's a couple levels of abstraction away from the right place to do it.

**Comment by davidfowl** [comment]
Arg ok I figured as much
