### ISSUE TITLE
NullReferenceException from XUnit.Runner.Dnx.Program.Main

### ISSUE THREAD

**Issue by Alxandr** [xunit/dnx.xunit#28]
Tried to set up testing on a new dnx project, and the following was the result:

![image](https://cloud.githubusercontent.com/assets/112334/7441499/a4e87fea-f0ea-11e4-905a-3360c184cd46.png)

**Comment by davidfowl** [comment]
There were some renames, we need a branch for beta5

**Comment by bradwilson** [comment]
DNX Beta 5 will be officially supported in xUnit.net Beta 3.

Until it's released, you can pull CI Beta 3 builds from [our CI MyGet feed](https://www.myget.org/F/xunit/https://www.myget.org/F/xunit/).

**Comment by Fosol** [comment]
"xunit": "2.1.0-beta3-build3029",
    "xunit.runner.dnx": "2.1.0-beta3-build99",
    "xunit.runner.visualstudio": "2.1.0-beta3-build1069",

trying to run "dnx . test" and it throw a System.NullReferenceException.
