### ISSUE TITLE
With a largish number of tests, the test runner never completes

### ISSUE THREAD

**Issue by matthewDDennis** [xunit/dnx.xunit#29]
Using VS 2015 RC, and dnx beta4 (too much happening on Beta5 to use it right now)
```json
    "dependencies": {
        "xunit":  "2.1.0-beta2-*",
        "xunit.runner.dnx": "2.1.0-beta2-*",
```

- with 57 tests, the test runner appears to execute all the tests, but doesn't 'finish'.
- Cancelling, and attempting to run any single or multiple test will not finish after that.
- Restarting VS will allow running single tests, and 30 tests, but 40 tests hangs and I can no longer run tests.
- Running the tests the command line works fine.
- xnunit(2.1.0-beta2-build2981)
- xunit.runner.dnx-beta2.build79)

**Comment by bradwilson** [comment]
Does this only happen inside Visual Studio, or does it also happen when running from the command line (i.e., `dnx . test`)?

Also, can you provide a repro project?

**Comment by matthewDDennis** [comment]
Works fine from the command lone.

-----Original Message-----

**Comment by matthewDDennis** [comment]
I just converted to Beta5 and both test runners  
- "xunit.runner.aspnet": "2.0.0-aspnet-beta5-*"
- "xunit.runner.dnx": "2.1.0-*"
are hanging in VS if I try and run 40 test, but work great from the command line.  I am suspecting a bug in Microsoft.Framework.TestHost

**Comment by matthewDDennis** [comment]
Sorry for the delay.
I've extracted a minimal project from my code to demo the issue.
It can be found at https://github.com/matthewDDennis/TestRunnerBugSample.
- you can run tests from a class successfully in VS
- if you attempt to run all test in VS it hangs
- all test run from command line.

**Comment by bradwilson** [comment]
The sample is attempting to use DNX Beta 5, but that is not supported by Visual Studio 2015 RC.

Please re-open with a repro that uses DNX Beta 4 + VS 2015 RC (or another supported version combination).
