### ISSUE TITLE
Don't only support TeamCity

### ISSUE THREAD

**Issue by Alxandr** [xunit/dnx.xunit#3]
Currently the test-runner is hard-coded to discover TeamCity and change it's output if it does. This is really bad practice, and does not support other CIs (like AppVeyor). The runner should have a plugin based architecture (or something akin to it), so that if I wrote my own CI that needed it's own format, I could create a output-formatter (or whatever you want to call it) to support xunit.

**Comment by giggio** [comment]
This is really important. It does not make any sense to hard code support for a specific CI server.

**Comment by kevinkuszyk** [comment]
+1 for this. In particular AppVeyor support.

**Comment by kevinkuszyk** [comment]
I found a work around for this.  We save the test results to an `xml` file  in our `build.cmd`: 

````
k test -xml .\xunit-results.xml
````

And then upload to AppVeyor using the on build finish script:

````
# upload results to AppVeyor
$wc = New-Object 'System.Net.WebClient'
$wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-results.xml))
````

More information [here](http://www.appveyor.com/docs/running-tests#uploading-xml-test-results).

**Comment by PureKrome** [comment]
again, +1 for this. AppVeyor user here. Moved off TC. But yeah ... specific CI support is blech :(

**Comment by bradwilson** [comment]
After RTM we will evaluate a generalized solution for all runners, not just ASP.NET or Console.

**Comment by bradwilson** [comment]
Shipping in 2.1 Beta 3.

**Comment by Alxandr** [comment]
Any where I can find explanation of this feature? As in, how to use it?

**Comment by bradwilson** [comment]
Are you asking how to get AppVeyor to work, or how to write your own?

Until we ship an official Beta 3 release, you can use builds from our [MyGet feed](https://www.myget.org/F/xunit/). Use `xunit` builds from `2.1.0-beta3-build3025` or later, and `xunit.runner.dnx` builds from `2.1.0-beta3-build95` or later. When you run DNX tests in your AppVeyor project, they just work: they will show up in the Tests tab of your AppVeyor project.

If you want to know how to write your own, the best places to start would be to look at the source for [DefaultRunnerReporter](https://github.com/xunit/xunit/blob/05826dcfd3cee97d93ff63201db0296933dd3511/src/xunit.runner.utility/Extensibility/DefaultRunnerReporter.cs) and [DefaultRunnerReporterMessageHandler](https://github.com/xunit/xunit/blob/05826dcfd3cee97d93ff63201db0296933dd3511/src/xunit.runner.utility/Extensibility/DefaultRunnerReporterMessageHandler.cs). The other runners (TeamCity, AppVeyor, etc.) are in [xunit.runner.reporters](https://github.com/xunit/xunit/tree/05826dcfd3cee97d93ff63201db0296933dd3511/src/xunit.runner.reporters), and there are desktop and DNX project builds (the former support the Console and MSBuild Runners; the latter supports the DNX Runner).
