### ISSUE TITLE
Inject available runtime dependencies through test class ctor

### ISSUE THREAD

**Issue by tugberkugurlu** [xunit/dnx.xunit#30]
DNX has some runtime components which are registered inside the runtime `IServiceProvider` implementation like `IApplicationEnvironment`, `ILibraryManager`, etc. It would be good if xunit dnx runner had a way of injecting this through the test class ctor.

Refer to http://stackoverflow.com/q/30111920/463785 for a sample use case.

**Comment by davidfowl** [comment]
See https://github.com/xunit/dnx.xunit/issues/27

**Comment by mdekrey** [comment]
+1; even if it's not through the test class ctor, given the reference @davidfowl made, such as a custom Fixture, this would be an incredibly useful addition for the `IApplicationEnvironment`.

**Comment by bradwilson** [comment]
Architecturally, this isn't really possible today. See the comments in #27.
