### ISSUE TITLE
The test runner should use IApplicationShutdown

### ISSUE THREAD

**Issue by Tragetaschen** [xunit/dnx.xunit#33]
aspnet/dnx#1795

Running the tests through `dnx . test --watch` currently does not end the running tests when a file on disk changes. This is because dnx' file watching signals the `IApplicationShutdown.ShutdownRequested` cancellation token, but nothing in the test runner uses this.

It would be great if a test run was cancelled when the CT is signaled.

**Comment by cherrydev** [comment]
Thanks for opening this, I was thinking of doing the same.  To elaborate more, the (presumed) goal is to get the test runner automatically re-running whenever the source code changes.  This could be done trivially using dnx's `--watch` option and xunit's `-wait` option and a .bat/.sh file that just re-ran the command over and over.
