### ISSUE TITLE
DNX Core 5.0 tests are not discovered in the TestExporer

### ISSUE THREAD

**Issue by lukaskabrt** [xunit/dnx.xunit#39]
It seems, that `xunit.runner.dnx` is unable to show tests in the Test Explorer window if the project doesn't use `dnx451` in the frameworks section. 

If `"dnx451": {}` is removed from the `project.json`, then all tests disappear from the Test Explorer, but they are still discovered by `dnx . test` command.

**project.json**

```
{
    "version": "1.0.0-*",
    "description": "",
    "authors": [ "" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
        "xunit": "2.1.0-beta2-build2981",
        "xunit.runner.dnx": "2.1.0-beta2-build79"
    },
    "commands": {
        "test": "xunit.runner.dnx"
    },
  "frameworks" : {
    "dnxcore50": {
        "dependencies": {
            "System.Collections": "4.0.10-beta-22816",
            "System.Linq": "4.0.0-beta-22816",
            "System.Threading": "4.0.10-beta-22816",
            "Microsoft.CSharp": "4.0.0-beta-22816"
        }
    },
    "dnx451": {}
  }
}
```

**Comment by bradwilson** [comment]
This is very likely a bug in the plugin owned by the ASP.NET team, which bridges DNX test runners with Visual Studio. You may want to address the issue with them. /cc @davidfowl

**Comment by bradwilson** [comment]
Closing now that it's been reported to the responsible team. If there turns out to be any issues in our runner here, please re-open the issue.
