### ISSUE TITLE
How to run cases in order?

### ISSUE THREAD

**Issue by txchen** [xunit/dnx.xunit#44]
Currently I am getting random order of test execution in my project, by typing `dnx . test`

Even if I specify -maxthreads 1 or -parallel none, it is still random order.

Is there a way to let the runner run cases in order, let's say for example, order by class Name?

**Comment by bradwilson** [comment]
The random-by-default is purposeful, as it helps people catch unexpected dependencies between the run orders of unit tests.

The ordering is extensible. This sample shows how to order test collections, and ordering tests within a given collection: https://github.com/xunit/samples.xunit/tree/master/TestOrderExamples (By default, each class is its own test collection.)

**Comment by bradwilson** [comment]
BTW, I should mention that while the sample only shows using test case orderers on a test class, you can also attach them to test collections and make them assembly-wide (using `[assembly: TestCaseOrderer(...)]` in your `GlobalAssemblyInfo.cs` file).

**Comment by txchen** [comment]
Thanks @bradwilson ! But is this working in dnx now?

I tried adding a file:
```
using System.Collections.Generic;
using System.Linq;
using Xunit;
using Xunit.Abstractions;

[assembly: TestCollectionOrderer("MyNamespace.DisplayNameOrderer", "My")]
[assembly: CollectionBehavior(DisableTestParallelization = true)]

namespace MyNamespace
{
    public class DisplayNameOrderer : ITestCollectionOrderer
    {
        public IEnumerable<ITestCollection> OrderTestCollections(IEnumerable<ITestCollection> testCollections)
        {
            return testCollections.OrderBy(collection => collection.DisplayName);
        }
    }
}
```

And I have my test cases in classes like Q001, Q002..., but I am still getting random order.

I also tried to put the [assebly:] in GlobalAssemblyInfo.cs, seems not helpful

**Comment by txchen** [comment]
Or do I have to add `[Collection("Xzy Test Collection")]` to every of my test class?

**Comment by bradwilson** [comment]
I haven't tested in specifically with DNX. It's possible that it's not working. Is `My` the name of your test assembly?

**Comment by txchen** [comment]
Oh yeah, after changing `my` to the assembly name (actually the folder name, since I only have project.json, and never defined an assembly name), it works!

Thanks a lot!
