### ISSUE TITLE
Accessing dependencies from test cases

### ISSUE THREAD

**Issue by yufeih** [xunit/dnx.xunit#48]
Is it possible to access dependencies from test cases?

```csharp
public class MyTest
{
    public MyTest(IApplicationEnvironment appEnv)
    {
          // Use appEnv
    }
}
```
This is currently not possible because test constructor is used for sharing fixtures.

**Comment by bradwilson** [comment]
Sorry, this is not possible. See https://github.com/xunit/dnx.xunit/issues/27#issuecomment-98568623
