### ISSUE TITLE
Poor perf on Mono

### ISSUE THREAD

**Issue by natemcmaster** [xunit/dnx.xunit#49]
Poor performance in test discovery and startup on Mono 4.0.2 can quadruple or more the total runtime of tests compare to full .NET or CoreCLR.

See https://github.com/aspnet/EntityFramework/issues/2574#issuecomment-120177298 for example. We confirmed it is the runner that adds lots of extra execution time.

**Comment by bradwilson** [comment]
The new "no app domain" switch should dramatically improve perf with Mono.

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#484
