### ISSUE TITLE
Visual Studio 2015 RC

### ISSUE THREAD

**Issue by Fosol** [xunit/dnx.xunit#50]
Installing the xunit requires manually adding a reference to System.Runtime.

I have to issues;
1) I can't get the unit tests to show up in the Visual Studio 2015 Test Explorer.
2) I can't run anything off the command line.

The unit tests do not show up in Visual Studio Test Explorer.
- I've installed a variation of NuGet Packages, but with no success.
- I've installed xunit and xunit.runner.dnx.
- I've added the commands "test": "xunit.runner.dnx"

I've also not been able to run the test one the command line.  "dnx" is not a recognized command.  How to run a command if the command window doesn't even know about "dnx"?

**Comment by Fosol** [comment]
I was able to execute the "dnx" command in a command window.  It however throws the following error;

"System.NullReferenceException: Object reference not set to an instance of an object. at Xunit.Runner.Dnx.Program.Main(String[] args)"

**Comment by Fosol** [comment]
"xunit": "2.1.0-beta3-build3029",
    "xunit.runner.dnx": "2.1.0-beta3-build99",
    "xunit.runner.visualstudio": "2.1.0-beta3-build1069",

**Comment by bradwilson** [comment]
VS 2015 RC (explicitly) supports DNX Beta 4 only, which means that only DNX Runner 2.1 Beta 2 actually works (reliably) in VS 2015 RC.

**Comment by bradwilson** [comment]
Assuming this is fixed; please re-open if it's not.

**Comment by jbrwn** [comment]
@bradwilson 

Did you actually test that this is fixed?  I am having the exact same issue in VS 2015 RC.  Tests run fine from the command line but do not work from test explorer in VS.   Here is my project.json

```
{
  "version": "1.0.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "xunit": "2.1.0-beta2-*",
    "xunit.runner.dnx": "2.1.0-beta2-*"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-22816",
        "System.Linq": "4.0.0-beta-22816",
        "System.Threading": "4.0.10-beta-22816",
        "Microsoft.CSharp": "4.0.0-beta-22816"
      }
    }
  }
}
```

**Comment by jbrwn** [comment]
Just tried again and its working.  I think i may have tested with an empty [Fact] method?  Not sure if that makes a difference or not.

**Comment by bradwilson** [comment]
Yes, we extensively test the appropriate betas with the appropriate versions of Visual Studio.

You can use DNX Beta 5 + xUnit.net 2.1 beta 3 with VS 2015 RTM.

**Comment by jbrwn** [comment]
Right on.  I will give beta3 a shot a when i get VS 2015 RTM installed.  Thanks!
