### ISSUE TITLE
Refactor at DNX causing System.MissingMethodException

### ISSUE THREAD

**Issue by Alxandr** [xunit/dnx.xunit#52]
A refactoring that just happened at DNX is causing a `System.MissingMethodException`. Should be fairly simple to fix as most things have just been renamed.

Full issue can be seen in printscreen below:

![image](https://cloud.githubusercontent.com/assets/112334/8838515/64738806-30cd-11e5-87a4-fec5be09a442.png)

**Comment by bradwilson** [comment]
Dup of #51.

**Comment by Alxandr** [comment]
Wow. Here I thought I was being a good netizen and checking the issues beforehand for dupes. Guess I forgot to check the PRs -.-

Oh, well, any idea when #51 you will start tracking b7?

**Comment by bradwilson** [comment]
Should be next week, once ASP.NET Beta 6 (and the UWP tooling for VS 2015) ship.
