### ISSUE TITLE
Code coverage in Visual Studio

### ISSUE THREAD

**Issue by Flavien** [xunit/dnx.xunit#54]
Is is possible to have code coverage displayed in Visual Studio when using the Visual Studio Test Runner?

    "dependencies": {
        "xunit": "2.1.0-*",
        "xunit.runner.dnx": "2.1.0-*"
    }

When I run "Analyze code coverage for selected tests", I only see the 4 XUnit assemblies in the "Code Coverage Result" window.

**Comment by bradwilson** [comment]
We don't control the availability of code coverage in this scenario. The issue must be taken up with whichever team is responsible for the `project.json` support for pluggable test frameworks (might be the ASP.NET team, might be the Visual Studio team; @davidfowl or @DamianEdwards would probably know).

**Comment by scabana** [comment]
Tried to get this working last week as well as vstest.console.exe, seems we're out of luck at this point in time :cry:

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#483
